Revert "Split HTML into many files"
This reverts commit 8348a67df1f9291f196d2fba56b2dd3a45342121.

There are some errors during initialization such as

TypeError: Cannot read property '$setPristine' of undefined

This will be attempted again during the refactoring